name: Trigger auto deployment for container-app-56xsr7rzantva

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-56xsr7rzantva-AutoDeployTrigger-decf6320-3cc6-4b07-8fe1-6d00bdaa825e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP56XSR7RZANTVA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP56XSR7RZANTVA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP56XSR7RZANTVA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry56xsr7rzantva.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP56XSR7RZANTVA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP56XSR7RZANTVA_REGISTRY_PASSWORD }}
          containerAppName: container-app-56xsr7rzantva
          resourceGroup: expresssampleb94d9f42
          imageToBuild: containerregistry56xsr7rzantva.azurecr.io/container-app-56xsr7rzantva:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


